from __future__ import annotations

from typing import Any


def _feature(
    order: int,
    name: str,
    feature_type: str,
    *,
    required: bool = False,
    unit: str | None = None,
    value_range: dict | list | str | None = None,
    enum_mapping: dict | list | str | None = None,
    default_strategy: str | None = None,
    missing_value_policy: str | None = None,
    notes: str | None = None,
) -> dict[str, Any]:
    return {
        'feature_order': order,
        'source_clinical_field': name,
        'model_feature_name': name,
        'feature_type': feature_type,
        'required': required,
        'optional': not required,
        'defaultable': default_strategy is not None,
        'unit': unit,
        'value_range': value_range,
        'enum_mapping': enum_mapping,
        'default_strategy': default_strategy,
        'missing_value_policy': missing_value_policy,
        'notes': notes,
    }


CAP_COP_CLINICAL_FEATURES = [
    _feature(1, 'Age', 'numeric', required=True, unit='years', missing_value_policy='consult_doctor_first', notes='Age is required for CAP/COP risk assessment and phenotype normalization.'),
    _feature(2, 'Sex', 'categorical', required=True, unit='category', value_range={'allowed': ['male', 'female', 'unknown']}, enum_mapping={'male': 'male', 'female': 'female', 'unknown': 'unknown'}, default_strategy='ask_doctor_then_unknown', missing_value_policy='consult_doctor_then_default', notes='Sex is required because the historical CAP/COP models were trained with sex-stratified calibration features.'),
    _feature(3, 'Temperature', 'numeric', required=True, unit='celsius', missing_value_policy='consult_doctor_first', notes='Temperature is a key infection severity indicator.'),
    _feature(4, 'HeartRate', 'numeric', required=False, unit='bpm', missing_value_policy='optional_no_action'),
    _feature(5, 'RespiratoryRate', 'numeric', required=True, unit='breaths_per_minute', missing_value_policy='consult_doctor_first', notes='Respiratory rate is required for acute severity assessment.'),
    _feature(6, 'SPO2', 'numeric', required=True, unit='percent', default_strategy='ask_doctor_then_unknown', missing_value_policy='consult_doctor_then_default', notes='Oxygen saturation is required for severity and triage calibration.'),
    _feature(7, 'SystolicBP', 'numeric', unit='mmHg', required=False),
    _feature(8, 'DiastolicBP', 'numeric', unit='mmHg', required=False),
    _feature(9, 'WBC', 'numeric', required=True, unit='10^9/L', missing_value_policy='consult_doctor_first', notes='WBC is required for inflammatory burden estimation.'),
    _feature(10, 'NeutrophilPercent', 'numeric', required=True, unit='percent', missing_value_policy='consult_doctor_first', notes='Neutrophil percentage is required for the historical CAP/COP feature family.'),
    _feature(11, 'LymphocytePercent', 'numeric', unit='percent', required=False),
    _feature(12, 'CRP', 'numeric', required=True, unit='mg/L', missing_value_policy='consult_doctor_first', notes='CRP is required in the clinical MLP training schema.'),
    _feature(13, 'Procalcitonin', 'numeric', unit='ng/mL', required=False, default_strategy='consult_doctor_if_possible'),
    _feature(14, 'ESR', 'numeric', unit='mm/h', required=False),
    _feature(15, 'Hemoglobin', 'numeric', unit='g/dL', required=False),
    _feature(16, 'Platelet', 'numeric', unit='10^9/L', required=False),
    _feature(17, 'Sodium', 'numeric', unit='mmol/L', required=False),
    _feature(18, 'Potassium', 'numeric', unit='mmol/L', required=False),
    _feature(19, 'Chloride', 'numeric', unit='mmol/L', required=False),
    _feature(20, 'BUN', 'numeric', unit='mg/dL', required=False),
    _feature(21, 'Creatinine', 'numeric', unit='mg/dL', required=False),
    _feature(22, 'ALT', 'numeric', unit='U/L', required=False),
    _feature(23, 'AST', 'numeric', unit='U/L', required=False),
    _feature(24, 'Albumin', 'numeric', unit='g/dL', required=False),
    _feature(25, 'Glucose', 'numeric', unit='mg/dL', required=False),
    _feature(26, 'Cough', 'boolean', unit='flag', required=False),
    _feature(27, 'Fever', 'boolean', unit='flag', required=False),
    _feature(28, 'Dyspnea', 'categorical', required=True, unit='category', value_range={'allowed': ['none', 'mild', 'moderate', 'severe', 'unknown']}, enum_mapping={'none': 'none', 'mild': 'mild', 'moderate': 'moderate', 'severe': 'severe', 'unknown': 'unknown'}, default_strategy='ask_doctor_then_unknown', missing_value_policy='consult_doctor_then_default', notes='Dyspnea severity was part of the historical CAP/COP input schema and must remain available.'),
    _feature(29, 'ChestPain', 'boolean', unit='flag', required=False),
    _feature(30, 'Wheeze', 'boolean', unit='flag', required=False),
    _feature(31, 'Crackles', 'boolean', unit='flag', required=False),
    _feature(32, 'Consolidation', 'boolean', required=True, unit='flag', missing_value_policy='consult_doctor_first', notes='Consolidation is required for the historical task family and must be auditable.'),
    _feature(33, 'PleuralEffusion', 'boolean', unit='flag', required=False),
    _feature(34, 'Infiltration', 'boolean', unit='flag', required=False),
    _feature(35, 'Striated_shadow.1', 'boolean', required=True, unit='flag', value_range={'allowed': [0, 1]}, enum_mapping={'0': 'absent', '1': 'present', 0: 'absent', 1: 'present'}, missing_value_policy='consult_doctor_first', notes='Must be preserved because it belongs to the historical CAP/COP task feature set.'),
    _feature(36, 'SmokingHistory', 'categorical', unit='category', required=False, value_range={'allowed': ['never', 'former', 'current', 'unknown']}, enum_mapping={'never': 'never', 'former': 'former', 'current': 'current', 'unknown': 'unknown'}, default_strategy='ask_doctor_then_unknown', missing_value_policy='consult_doctor_then_default'),
]

PULMONARY_TRIAGE_FEATURES = [
    _feature(1, 'Age', 'numeric', required=True, unit='years', missing_value_policy='consult_doctor_first', notes='Age is required for pulmonary triage support.'),
    _feature(2, 'RespiratoryRate', 'numeric', required=True, unit='breaths_per_minute', missing_value_policy='consult_doctor_first', notes='Respiratory rate is required for triage scoring.'),
    _feature(3, 'SPO2', 'numeric', required=True, unit='percent', missing_value_policy='consult_doctor_first', notes='SPO2 is required for triage escalation.'),
    _feature(4, 'Dyspnea', 'categorical', required=True, unit='category', value_range={'allowed': ['none', 'mild', 'moderate', 'severe', 'unknown']}, enum_mapping={'none': 'none', 'mild': 'mild', 'moderate': 'moderate', 'severe': 'severe', 'unknown': 'unknown'}, default_strategy='ask_doctor_then_unknown', missing_value_policy='consult_doctor_then_default', notes='Dyspnea severity is required for pulmonary triage.'),
    _feature(5, 'Wheeze', 'boolean', unit='flag', required=False),
    _feature(6, 'OxygenNeed', 'boolean', unit='flag', required=False),
]

CAP_COP_MULTIMODAL_FEATURES = [
    CAP_COP_CLINICAL_FEATURES[0],
    CAP_COP_CLINICAL_FEATURES[1],
    CAP_COP_CLINICAL_FEATURES[2],
    CAP_COP_CLINICAL_FEATURES[4],
    CAP_COP_CLINICAL_FEATURES[5],
    CAP_COP_CLINICAL_FEATURES[8],
    CAP_COP_CLINICAL_FEATURES[11],
    CAP_COP_CLINICAL_FEATURES[27],
    CAP_COP_CLINICAL_FEATURES[31],
    CAP_COP_CLINICAL_FEATURES[34],
    CAP_COP_CLINICAL_FEATURES[33],
    CAP_COP_CLINICAL_FEATURES[35],
]

CAP_COP_IMAGING_FEATURES = [
    CAP_COP_CLINICAL_FEATURES[0],
    CAP_COP_CLINICAL_FEATURES[1],
    CAP_COP_CLINICAL_FEATURES[4],
    CAP_COP_CLINICAL_FEATURES[5],
    CAP_COP_CLINICAL_FEATURES[27],
    CAP_COP_CLINICAL_FEATURES[31],
    CAP_COP_CLINICAL_FEATURES[33],
    CAP_COP_CLINICAL_FEATURES[34],
]

FEATURE_SETS: dict[str, dict[str, Any]] = {
    'cap_cop_clinical_feature_set_v1': {
        'feature_set_id': 'cap_cop_clinical_feature_set_v1',
        'feature_set_key': 'cap_cop_clinical_feature_set_v1',
        'feature_set_name': 'CAP/COP Clinical Feature Set v1',
        'disease_task_code': 'cap_cop',
        'schema_version': 'v1',
        'description': 'CAP/COP task-family clinical attribute collection shared across multiple models.',
        'features': CAP_COP_CLINICAL_FEATURES,
    },
    'pulmonary_triage_clinical_feature_set_v1': {
        'feature_set_id': 'pulmonary_triage_clinical_feature_set_v1',
        'feature_set_key': 'pulmonary_triage_clinical_feature_set_v1',
        'feature_set_name': 'Pulmonary Triage Clinical Feature Set v1',
        'disease_task_code': 'pulmonary_triage',
        'schema_version': 'v1',
        'description': 'Task-specific clinical attribute collection for pulmonary triage.',
        'features': PULMONARY_TRIAGE_FEATURES,
    },
}

MODEL_INPUT_SCHEMA_PROFILES: dict[str, dict[str, Any]] = {
    'clinical_mlp_cap_cop_input_schema_v1': {
        'feature_set_id': 'cap_cop_clinical_feature_set_v1',
        'feature_set_key': 'cap_cop_clinical_feature_set_v1',
        'feature_set_name': 'CAP/COP Clinical Feature Set v1',
        'schema_id': 'clinical_mlp_cap_cop_input_schema_v1',
        'schema_key': 'clinical_mlp_cap_cop_input_schema_v1',
        'schema_name': 'clinical_mlp_cap_cop_input_schema_v1',
        'schema_version': 'v1',
        'disease_task': 'cap_cop',
        'supported_disease_tasks': ['cap_cop', 'CAP_COP_CLASSIFICATION'],
        'supported_modalities': ['clinical_table'],
        'lifecycle_status': 'default',
        'model_family': 'clinical_mlp',
        'preprocess_artifact_ref': 'metadata-only://cap_cop/clinical_mlp/preprocess/v1',
        'limitations': ['metadata_only', 'no_model_loaded', 'no_live_inference'],
        'feature_requirements': CAP_COP_CLINICAL_FEATURES,
    },
    'multimodal_resnet18_cap_cop_input_schema_v1': {
        'feature_set_id': 'cap_cop_clinical_feature_set_v1',
        'feature_set_key': 'cap_cop_clinical_feature_set_v1',
        'feature_set_name': 'CAP/COP Clinical Feature Set v1',
        'schema_id': 'multimodal_resnet18_cap_cop_input_schema_v1',
        'schema_key': 'multimodal_resnet18_cap_cop_input_schema_v1',
        'schema_name': 'multimodal_resnet18_cap_cop_input_schema_v1',
        'schema_version': 'v1',
        'disease_task': 'cap_cop',
        'supported_disease_tasks': ['cap_cop', 'CAP_COP_CLASSIFICATION'],
        'supported_modalities': ['clinical_table', 'ct_image', 'mri_image'],
        'lifecycle_status': 'approved',
        'model_family': 'multimodal_resnet18',
        'preprocess_artifact_ref': 'metadata-only://cap_cop/multimodal_resnet18/preprocess/v1',
        'limitations': ['metadata_only', 'stub_schema_only', 'no_live_inference'],
        'feature_requirements': CAP_COP_MULTIMODAL_FEATURES,
    },
    'imaging_resnet18_cap_cop_input_schema_v1': {
        'feature_set_id': 'cap_cop_clinical_feature_set_v1',
        'feature_set_key': 'cap_cop_clinical_feature_set_v1',
        'feature_set_name': 'CAP/COP Clinical Feature Set v1',
        'schema_id': 'imaging_resnet18_cap_cop_input_schema_v1',
        'schema_key': 'imaging_resnet18_cap_cop_input_schema_v1',
        'schema_name': 'imaging_resnet18_cap_cop_input_schema_v1',
        'schema_version': 'v1',
        'disease_task': 'cap_cop',
        'supported_disease_tasks': ['cap_cop', 'CAP_COP_CLASSIFICATION'],
        'supported_modalities': ['ct_image', 'mri_image'],
        'lifecycle_status': 'shadow',
        'model_family': 'imaging_resnet18',
        'preprocess_artifact_ref': 'metadata-only://cap_cop/imaging_resnet18/preprocess/v1',
        'limitations': ['metadata_only', 'stub_schema_only', 'no_live_inference'],
        'feature_requirements': CAP_COP_IMAGING_FEATURES,
    },
    'clinical_mlp_pulmonary_triage_input_schema_v1': {
        'feature_set_id': 'pulmonary_triage_clinical_feature_set_v1',
        'feature_set_key': 'pulmonary_triage_clinical_feature_set_v1',
        'feature_set_name': 'Pulmonary Triage Clinical Feature Set v1',
        'schema_id': 'clinical_mlp_pulmonary_triage_input_schema_v1',
        'schema_key': 'clinical_mlp_pulmonary_triage_input_schema_v1',
        'schema_name': 'clinical_mlp_pulmonary_triage_input_schema_v1',
        'schema_version': 'v1',
        'disease_task': 'pulmonary_triage',
        'supported_disease_tasks': ['pulmonary_triage'],
        'supported_modalities': ['clinical_table'],
        'lifecycle_status': 'default',
        'model_family': 'clinical_mlp',
        'preprocess_artifact_ref': 'metadata-only://pulmonary_triage/clinical_mlp/preprocess/v1',
        'limitations': ['metadata_only', 'no_model_loaded', 'no_live_inference'],
        'feature_requirements': PULMONARY_TRIAGE_FEATURES,
    },
}

TASK_MODEL_FILTERS: dict[str, dict[str, str]] = {
    'cap_cop': {'disease_agent': 'capcop_agent', 'task_type': 'risk_assessment'},
    'pulmonary_triage': {'disease_agent': 'pulmonary_triage', 'task_type': 'diagnosis_support'},
}

DISEASE_TASK_SCHEMA_ORDER: dict[str, list[str]] = {
    'cap_cop': [
        'clinical_mlp_cap_cop_input_schema_v1',
        'multimodal_resnet18_cap_cop_input_schema_v1',
        'imaging_resnet18_cap_cop_input_schema_v1',
    ],
    'pulmonary_triage': [
        'clinical_mlp_pulmonary_triage_input_schema_v1',
    ],
}
